---
features:
  - |
    The following parameters have been added to the ``ironic::pxe`` class, to
    allow more flexible configurations of the virtual host serving image files.

    - ``vhost_priority``
    - ``vhost_options``
    - ``vhost_config``
